services:
  logs-writing:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: logs-writing
    networks:
      - internal-net

networks:
  internal-net:
    name: internal-net
    external: true
