services:
  keycloak:
    image: keycloak/keycloak:26.1.0
    ports:
      - 8080:8080
    env_file:
      - .env
    command: start
    networks:
      - internal-net

networks:
  internal-net:
    name: internal-net
    external: true
