services:
  keycloak:
    image: keycloak/keycloak:26.1.0
    ports:
      - 8080:8080
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://master:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_HTTP_ENABLED: 'true'
      # KC_PROXY: passthrough
      KC_HOSTNAME: http://localhost:8080
      KC_HOSTNAME_STRICT: true
      # KC_HOSTNAME_STRICT_HTTPS: true
    command: start
    networks:
      - internal-net

networks:
  internal-net:
    name: internal-net
