require('dotenv').config();

module.exports = {
    master_db: process.env.MASTER_NAME,
    replica1: process.env.STANDBY1_NAME,
    replica2: process.env.STANDBY2_NAME,
    db_user: process.env.DB_USER,
    db_user_password: process.env.DB_USER_PASSWORD,
    db_port: process.env.DB_PORT,
    db_name: process.env.DB_NAME,
    port: process.env.PORT || 3000,
    logs_topic: process.env.KAFKA_LOGS,
    cv_parsing_topic: process.env.KAFKA_CV_PARSING,
    job_parsing_topic: process.env.KAFKA_JOB_PARSING,
    cv_embedding: process.env.KAFKA_CV_EMBEDDING_GENERATION,
    job_embedding_topic: process.env.KAFKA_JOB_EMBEDDING_GENERATION,
    profile_embedding_topic: process.env.KAFKA_PROFILE_EMBEDDING_GENERATION,
    brokers: [process.env.KAFKA_BROKER1, process.env.KAFKA_BROKER2],
    minio_user: process.env.MINIO_USER,
    minio_password: process.env.MINIO_PASSWORD,
    desc_order: -1,
    asc_order: 1,
    candidate_status_pending: 1,
    candidate_status_accepted: 2,
    candidate_status_rejected: 3,
    pagination_limit: 10,
    maxNameLength: 30,
    role: {
        jobSeeker: 'jobSeeker',
        company: 'company',
        recruiter: 'recruiter'
    },
    action_types: {
        move_candidate: 1,
        create_template: 2,
        remove_recruiter: 3,
        add_recruiter: 4,
        create_assessment: 5,
        remove_assessment: 6,
        create_recruitement_process: 7,
        remove_recruitement_process: 8,
        assign_candidate: 9,
        unassign_candidate: 10,
        create_job: 11,
        close_job: 12
    },
    minNameLength: 1,
    maxOverviewLength: 500,
    minOverviewLength: 1,
    minYear: 1800,
    minCompanySize: 1,
    maxCompanySize: 100000000,
    minIndustryLength: 1,
    maxIndustryLength: 50,
    minLocationLength: 1,
    maxLocationLength: 50,
    minIndustriesArrayLength: 1,
    maxIndustriesArrayLength: 300,
    minLocationsArrayLength: 1,
    maxLocationsArrayLength: 300,
    imagesBucketName: 'images-bucket',
    cvsBucketName: 'cvs-bucket'
};
