services:
  email-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: email-server
    networks:
      - internal-net

networks:
  internal-net:
    name: internal-net
    external: true
