services:
  api:
    image: node:22.13.1-bookworm-slim
    volumes:
      - .:/src
    networks:
      - internal-net
    env_file:
      - .env
    working_dir: /src
    command: ["npm", "start"]
    scale: 2

networks:
  internal-net:
    name: internal-net
    external: true
