services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    volumes:
      - .:/src
    networks:
      - internal-net
    env_file:
      - .env

networks:
  internal-net:
    name: internal-net
    external: true
