services:
  master:
    image: postgres:17.2
    container_name: master
    ports:
      - 5432:5432
    volumes:
      - ./master/data:/var/lib/postgresql/data
      - ./scripts/create_users.sql:/docker-entrypoint-initdb.d/create_users.sql
      - ./scripts/init_table.sh:/docker-entrypoint-initdb.d/init_table.sh
      - ./scripts/table_creation.sql:/scripts/table_creation.sql
      - ./scripts/set_permissions.sql:/docker-entrypoint-initdb.d/set_permissions.sql
    networks:
      - internal-net
    env_file:
      - .env

  standby1:
    image: postgres:17.2
    container_name: standby1
    volumes:
      - ./standby1/data:/var/lib/postgresql/data
      - ./scripts/create_standby_signal.sh:/docker-entrypoint-initdb.d/create_standby_signal.sh
    networks:
      - internal-net
    depends_on:
      - master
    env_file:
      - .env

  standby2:
    image: postgres:17.2
    container_name: standby2
    volumes:
      - ./standby2/data:/var/lib/postgresql/data
      - ./scripts/create_standby_signal.sh:/docker-entrypoint-initdb.d/create_standby_signal.sh
    networks:
      - internal-net
    depends_on:
      - master
    env_file:
      - .env

networks:
  internal-net:
    name: internal-net
    driver: bridge
    ipam:
      config:
        - subnet: "10.0.0.0/24"
