services:
  master:
    image: postgres:17.2
    container_name: master
    volumes:
      - ./master/data:/var/lib/postgresql/data
      - ./scripts/create_replication_user.sql:/docker-entrypoint-initdb.d/create_replication_user.sql
    networks:
      - db-net
    env_file:
      - .env

  standby1:
    image: postgres:17.2
    container_name: standby1
    volumes:
      - ./standby1/data:/var/lib/postgresql/data
      - ./scripts/create_standby_signal.sh:/docker-entrypoint-initdb.d/create_standby_signal.sh
    networks:
      - db-net
    depends_on:
      - master
    env_file:
      - .env

  standby2:
    image: postgres:17.2
    container_name: standby2
    volumes:
      - ./standby2/data:/var/lib/postgresql/data
      - ./scripts/create_standby_signal.sh:/docker-entrypoint-initdb.d/create_standby_signal.sh
    networks:
      - db-net
    depends_on:
      - master
    env_file:
      - .env

networks:
  db-net:
    name: db-net
    driver: bridge
    ipam:
      config:
        - subnet: "10.0.0.0/24"
