services:
  master:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    container_name: master
    ports:
      - "5432:5432"
    volumes:
      - ./master/data:/var/lib/postgresql/data
      - ./scripts/create_users.sql:/docker-entrypoint-initdb.d/create_users.sql
      - ./scripts/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - ./scripts/init_table.sh:/docker-entrypoint-initdb.d/init_table.sh
      - ./scripts:/scripts
    networks:
      - internal-net
    env_file:
      - .env


  standby1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: standby1
    volumes:
      - ./standby1/data:/var/lib/postgresql/data
      - ./scripts/create_standby_signal.sh:/docker-entrypoint-initdb.d/create_standby_signal.sh
    networks:
      - internal-net
    depends_on:
      - master
    env_file:
      - .env
    ports:
      - "5433:5432"



  standby2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: standby2
    volumes:
      - ./standby2/data:/var/lib/postgresql/data
      - ./scripts/create_standby_signal.sh:/docker-entrypoint-initdb.d/create_standby_signal.sh
    networks:
      - internal-net
    depends_on:
      - master
    env_file:
      - .env
    ports:
      - "5434:5432"

networks:
  internal-net:
    name: internal-net
    driver: bridge
    ipam:
      config:
        - subnet: "10.0.0.0/24"
